"""initial schema

Revision ID: 2a6f0ac50e94
Revises: 
Create Date: 2026-05-30 13:04:07.503960

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2a6f0ac50e94'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('benchmark_version', sa.String(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('solve_rate', sa.Float(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_runs'))
    )
    op.create_table('task_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('wall_clock_seconds', sa.Float(), nullable=False),
    sa.Column('failure_mode', sa.String(), nullable=True),
    sa.Column('tool_counts', sa.JSON(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('eval_exit_code', sa.Integer(), nullable=True),
    sa.Column('eval_output', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['benchmark_runs.id'], name=op.f('fk_task_results_run_id_benchmark_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_results'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_results')
    op.drop_table('benchmark_runs')
    # ### end Alembic commands ###
